spring:
  application:
    name: student_sender_bot
  datasource:
    url: jdbc:postgresql://localhost:5432/student_sender_bot
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: redis
      port: 6379
telegram:
  bot:
    username: student_sender_bot
    token: 7466690263:AAGOYLoIpwksOKfPZPbEHBQSPmk-RPajN9o
cron:
  send-student:
    time-interval: 0 */10 * * * *
