spring:
  application:
    name: student_sender_bot
  datasource:
    url: jdbc:postgresql://localhost:5432/student_sender_bot
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: update
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
telegram:
  bot:
    username: student_sender_bot
    token: 7466690263:AAGOYLoIpwksOKfPZPbEHBQSPmk-RPajN9o
cron:
  send-student:
    time-interval: 0 */10 * * * *
const:
  student:
    reg:
      limit: 1
  group:
    without:
      name:
        Отсутствует